/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.imbochfckyeahprojects.finalproject;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.ArrayList;

/**
 *
 * @author imbochfuckyeah
 */
public class addtoticket extends javax.swing.JFrame {


    ArrayList<newticket> ticketsAsigneds = new ArrayList<>();

    /**
     * Creates new form addtoteam
     */
    public addtoticket() {
        initComponents();
        this.setLocationRelativeTo(null);
        setComboTeam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbackground = new javax.swing.JPanel();
        jdivclass = new javax.swing.JPanel();
        jtitle = new javax.swing.JLabel();
        jsubtitle = new javax.swing.JLabel();
        btcreate = new javax.swing.JButton();
        jticket = new javax.swing.JComboBox<>();
        jbackmenu = new javax.swing.JLabel();
        jmemberuser = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        datateamusers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbackground.setBackground(new java.awt.Color(0, 153, 204));

        jdivclass.setBackground(new java.awt.Color(255, 255, 255));

        jtitle.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jtitle.setForeground(new java.awt.Color(102, 102, 102));
        jtitle.setText("Add ticket to user");

        jsubtitle.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jsubtitle.setForeground(new java.awt.Color(0, 153, 204));
        jsubtitle.setText("only user with rol member");

        btcreate.setBackground(new java.awt.Color(0, 153, 204));
        btcreate.setFont(new java.awt.Font("Montserrat", 1, 15)); // NOI18N
        btcreate.setForeground(new java.awt.Color(255, 255, 255));
        btcreate.setText("adduser");
        btcreate.setBorder(null);
        btcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcreateActionPerformed(evt);
            }
        });

        jticket.setBackground(new java.awt.Color(249, 249, 249));
        jticket.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jticket.setForeground(new java.awt.Color(153, 153, 153));
        jticket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select user member" }));
        jticket.setBorder(null);

        jbackmenu.setFont(new java.awt.Font("Comfortaa", 0, 10)); // NOI18N
        jbackmenu.setForeground(new java.awt.Color(102, 102, 102));
        jbackmenu.setText("Back to menu");
        jbackmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbackmenuMouseClicked(evt);
            }
        });

        jmemberuser.setBackground(new java.awt.Color(249, 249, 249));
        jmemberuser.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jmemberuser.setForeground(new java.awt.Color(153, 153, 153));
        jmemberuser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ticket" }));
        jmemberuser.setToolTipText("");
        jmemberuser.setBorder(null);
        jmemberuser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jmemberuserItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jdivclassLayout = new javax.swing.GroupLayout(jdivclass);
        jdivclass.setLayout(jdivclassLayout);
        jdivclassLayout.setHorizontalGroup(
            jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdivclassLayout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(jbackmenu)
                .addGap(120, 120, 120))
            .addGroup(jdivclassLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdivclassLayout.createSequentialGroup()
                        .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtitle)
                            .addComponent(jsubtitle))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jmemberuser, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btcreate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jticket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdivclassLayout.setVerticalGroup(
            jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdivclassLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(jtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jmemberuser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jticket, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btcreate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jbackmenu)
                .addContainerGap())
        );

        datateamusers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(datateamusers);

        javax.swing.GroupLayout jbackgroundLayout = new javax.swing.GroupLayout(jbackground);
        jbackground.setLayout(jbackgroundLayout);
        jbackgroundLayout.setHorizontalGroup(
            jbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdivclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );
        jbackgroundLayout.setVerticalGroup(
            jbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbackgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addGroup(jbackgroundLayout.createSequentialGroup()
                        .addComponent(jdivclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcreateActionPerformed
        // TODO add your handling code here:
        for(newticket t: masterclass.ticket){
            if(t.getTitle().equals(jticket.getSelectedItem().toString())){
                t.setUserasigned(jmemberuser.getSelectedItem().toString());
                t.setTeamasigned(menuusers.teamcookie);
                t.setStatus("In process");
            break;
            }
        }
        //jusername.setSelectedIndex(0);
        filterUsers();
        setdatable(ticketsAsigneds);
    }//GEN-LAST:event_btcreateActionPerformed

    private void setComboTeam(){
        jmemberuser.setModel(new DefaultComboBoxModel<>(new String[]{
                "Select user member to asigned",
        }));

        for (newusers u : masterclass.users) {
            if(u.getRol().equals("Team member user")&&u.getTeam().equals(menuusers.teamcookie)){
                jmemberuser.addItem(u.getName());
            }
        }
    }

    private void jbackmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbackmenuMouseClicked
        // TODO add your handling code here:
        menuusers view = new menuusers(menuusers.user);
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbackmenuMouseClicked

    private void jmemberuserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jmemberuserItemStateChanged
        // TODO add your handling code here:
        filterUsers();
        setdatable(ticketsAsigneds);

    }//GEN-LAST:event_jmemberuserItemStateChanged

    private void filterUsers(){
        String teamselected = jmemberuser.getSelectedItem().toString();
        ArrayList<newticket> ticketNotAsigned = new ArrayList<>();
        ArrayList<newticket> ticketAsigned = new ArrayList<>();

        for(newticket u : masterclass.ticket){
            if(u.getUserasigned()== null){
                ticketNotAsigned.add(u);
            }else if(u.getUserasigned().isEmpty() || u.getUserasigned().isBlank()) {
                ticketNotAsigned.add(u);
            }else{
                if(u.getUserasigned().equals(teamselected)){
                    ticketAsigned.add(u);
                }
            }
        }

        jticket.setModel(new DefaultComboBoxModel<>(new String[]{
                "Select ticket",
        }));

        for (newticket t : ticketNotAsigned) {
            jticket.addItem(t.getTitle());
        }
        ticketsAsigneds = ticketAsigned;
    }

    private void setdatable(ArrayList<newticket> ticket){
        DefaultTableModel dataM = new DefaultTableModel(new String[]{"Id", "Title", "Descrip", "Date i", "User c", "User a", "Team a", "Date f"}, ticket.size());
            datateamusers.setModel(dataM);

            TableModel model = datateamusers.getModel();

            for (int i = 0; i < ticket.size(); i++) {
                newticket datau = ticket.get(i);
                model.setValueAt(datau.getId(), i, 0);
                model.setValueAt(datau.getTitle(), i, 1);
                model.setValueAt(datau.getDescrip(), i, 2);
                model.setValueAt(datau.getStartdate(), i, 3);
                model.setValueAt(datau.getUsercreated(), i, 4);
                model.setValueAt(datau.getUserasigned(), i, 5);
                model.setValueAt(datau.getTeamasigned(), i, 6);
                model.setValueAt(datau.getFinishdate(), i, 7);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcreate;
    private javax.swing.JTable datateamusers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jbackground;
    private javax.swing.JLabel jbackmenu;
    private javax.swing.JPanel jdivclass;
    private javax.swing.JComboBox<String> jmemberuser;
    private javax.swing.JLabel jsubtitle;
    private javax.swing.JComboBox<String> jticket;
    private javax.swing.JLabel jtitle;
    // End of variables declaration//GEN-END:variables
}
