/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.imbochfckyeahprojects.finalproject;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.ArrayList;

/**
 *
 * @author imbochfuckyeah
 */
public class addtoteam extends javax.swing.JFrame {


    ArrayList<newusers> usersTeamG = new ArrayList<>();

    /**
     * Creates new form addtoteam
     */
    public addtoteam() {
        initComponents();
        this.setLocationRelativeTo(null);
        setComboTeam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbackground = new javax.swing.JPanel();
        jdivclass = new javax.swing.JPanel();
        jtitle = new javax.swing.JLabel();
        jsubtitle = new javax.swing.JLabel();
        btcreate = new javax.swing.JButton();
        jusername = new javax.swing.JComboBox<>();
        jbackmenu = new javax.swing.JLabel();
        jteamname = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        datateamusers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbackground.setBackground(new java.awt.Color(0, 153, 204));

        jdivclass.setBackground(new java.awt.Color(255, 255, 255));

        jtitle.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jtitle.setForeground(new java.awt.Color(102, 102, 102));
        jtitle.setText("Add user to team");

        jsubtitle.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jsubtitle.setForeground(new java.awt.Color(0, 153, 204));
        jsubtitle.setText("only user with rol member");

        btcreate.setBackground(new java.awt.Color(0, 153, 204));
        btcreate.setFont(new java.awt.Font("Montserrat", 1, 15)); // NOI18N
        btcreate.setForeground(new java.awt.Color(255, 255, 255));
        btcreate.setText("adduser");
        btcreate.setBorder(null);
        btcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcreateActionPerformed(evt);
            }
        });

        jusername.setBackground(new java.awt.Color(249, 249, 249));
        jusername.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jusername.setForeground(new java.awt.Color(153, 153, 153));
        jusername.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select user member" }));
        jusername.setBorder(null);

        jbackmenu.setFont(new java.awt.Font("Comfortaa", 0, 10)); // NOI18N
        jbackmenu.setForeground(new java.awt.Color(102, 102, 102));
        jbackmenu.setText("Back to menu");
        jbackmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbackmenuMouseClicked(evt);
            }
        });

        jteamname.setBackground(new java.awt.Color(249, 249, 249));
        jteamname.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jteamname.setForeground(new java.awt.Color(153, 153, 153));
        jteamname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select team" }));
        jteamname.setToolTipText("");
        jteamname.setBorder(null);
        jteamname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jteamnameItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jdivclassLayout = new javax.swing.GroupLayout(jdivclass);
        jdivclass.setLayout(jdivclassLayout);
        jdivclassLayout.setHorizontalGroup(
            jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdivclassLayout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(jbackmenu)
                .addGap(120, 120, 120))
            .addGroup(jdivclassLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdivclassLayout.createSequentialGroup()
                        .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtitle)
                            .addComponent(jsubtitle))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jteamname, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btcreate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jusername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdivclassLayout.setVerticalGroup(
            jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdivclassLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(jtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jteamname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jusername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btcreate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jbackmenu)
                .addContainerGap())
        );

        datateamusers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(datateamusers);

        javax.swing.GroupLayout jbackgroundLayout = new javax.swing.GroupLayout(jbackground);
        jbackground.setLayout(jbackgroundLayout);
        jbackgroundLayout.setHorizontalGroup(
            jbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdivclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );
        jbackgroundLayout.setVerticalGroup(
            jbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbackgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addGroup(jbackgroundLayout.createSequentialGroup()
                        .addComponent(jdivclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcreateActionPerformed
        // TODO add your handling code here:
        for(newusers u: masterclass.users){
            if(u.getUser().equals(jusername.getSelectedItem().toString())){
                u.setTeam(jteamname.getSelectedItem().toString());
            break;
            }
        }
        //jusername.setSelectedIndex(0);
        filterUsers();
        setdatable(usersTeamG);
    }//GEN-LAST:event_btcreateActionPerformed

    private void setComboTeam(){
        jteamname.setModel(new DefaultComboBoxModel<>(new String[]{
                "Select team",
        }));

        for (newteam t : masterclass.team) {
            jteamname.addItem(t.getTeamname());
        }
    }

    private void jbackmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbackmenuMouseClicked
        // TODO add your handling code here:
        menuadmin m = new menuadmin();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbackmenuMouseClicked

    private void jteamnameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jteamnameItemStateChanged
        // TODO add your handling code here:

        filterUsers();
        setdatable(usersTeamG);

    }//GEN-LAST:event_jteamnameItemStateChanged

    private void filterUsers(){
        String teamselected = jteamname.getSelectedItem().toString();
        ArrayList<newusers> usersNoTeam = new ArrayList<>();
        ArrayList<newusers> usersTeam = new ArrayList<>();

        for(newusers u : masterclass.users){
            if(u.getTeam() == null){
                usersNoTeam.add(u);
            }else if(u.getTeam().isEmpty()) {
                usersNoTeam.add(u);
            }else{
                if(u.getTeam().equals(teamselected)){
                    usersTeam.add(u);
                }
            }
        }

        jusername.setModel(new DefaultComboBoxModel<>(new String[]{
                "Select user member to add",
        }));

        for (newusers u : usersNoTeam) {
            if(u.getRol().equals("Team member user")){
                jusername.addItem(u.getUser());
            }
        }
        usersTeamG = usersTeam;
    }

    private void setdatable(ArrayList<newusers> users){
        DefaultTableModel dataM = new DefaultTableModel(new String[]{"Name", "Lastname", "Email", "User", "Rol", "Departament", "Team"}, users.size());
        datateamusers.setModel(dataM);

        TableModel modelM = datateamusers.getModel();

        for (int i = 0; i < users.size(); i++) {
            newusers datau = users.get(i);
            modelM.setValueAt(datau.getName(), i, 0);
            modelM.setValueAt(datau.getLastname(), i, 1);
            modelM.setValueAt(datau.getEmail(), i, 2);
            modelM.setValueAt(datau.getUser(), i, 3);
            modelM.setValueAt(datau.getRol(), i, 4);
            modelM.setValueAt(datau.getDepartament(), i, 5);
            modelM.setValueAt(datau.getTeam(), i, 6);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcreate;
    private javax.swing.JTable datateamusers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jbackground;
    private javax.swing.JLabel jbackmenu;
    private javax.swing.JPanel jdivclass;
    private javax.swing.JLabel jsubtitle;
    private javax.swing.JComboBox<String> jteamname;
    private javax.swing.JLabel jtitle;
    private javax.swing.JComboBox<String> jusername;
    // End of variables declaration//GEN-END:variables
}
