/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.imbochfckyeahprojects.finalproject;

import javax.swing.JOptionPane;
import java.util.regex.*;

/**
 *
 * @author imbochfuckyeah
 */
public class createuser extends javax.swing.JFrame {

    /**
     * Creates new form createuser
     */
    public createuser() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbackground = new javax.swing.JPanel();
        jdivclass = new javax.swing.JPanel();
        jtitle = new javax.swing.JLabel();
        jsubtitle = new javax.swing.JLabel();
        jnewUser = new javax.swing.JTextField();
        btcreate = new javax.swing.JButton();
        jnewPassword = new javax.swing.JPasswordField();
        jnewName = new javax.swing.JTextField();
        jnewLastname = new javax.swing.JTextField();
        jnewEmail = new javax.swing.JTextField();
        jbackmenu = new javax.swing.JLabel();
        jnewrol = new javax.swing.JComboBox<>();
        jnewAge = new javax.swing.JTextField();
        jnewDepartament = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbackground.setBackground(new java.awt.Color(0, 153, 204));

        jdivclass.setBackground(new java.awt.Color(255, 255, 255));

        jtitle.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jtitle.setForeground(new java.awt.Color(102, 102, 102));
        jtitle.setText("Create new user");

        jsubtitle.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jsubtitle.setForeground(new java.awt.Color(0, 153, 204));
        jsubtitle.setText("Create new user with rol");

        jnewUser.setBackground(new java.awt.Color(249, 249, 249));
        jnewUser.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jnewUser.setForeground(new java.awt.Color(153, 153, 153));
        jnewUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jnewUser.setText("User");
        jnewUser.setToolTipText("");
        jnewUser.setBorder(null);
        jnewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnewUserActionPerformed(evt);
            }
        });

        btcreate.setBackground(new java.awt.Color(0, 153, 204));
        btcreate.setFont(new java.awt.Font("Montserrat", 1, 15)); // NOI18N
        btcreate.setForeground(new java.awt.Color(255, 255, 255));
        btcreate.setText("Create user");
        btcreate.setBorder(null);
        btcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcreateActionPerformed(evt);
            }
        });

        jnewPassword.setBackground(new java.awt.Color(249, 249, 249));
        jnewPassword.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jnewPassword.setForeground(new java.awt.Color(153, 153, 153));
        jnewPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jnewPassword.setText("password");
        jnewPassword.setBorder(null);
        jnewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnewPasswordActionPerformed(evt);
            }
        });

        jnewName.setBackground(new java.awt.Color(249, 249, 249));
        jnewName.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jnewName.setForeground(new java.awt.Color(153, 153, 153));
        jnewName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jnewName.setText("Name");
        jnewName.setToolTipText("");
        jnewName.setBorder(null);
        jnewName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnewNameActionPerformed(evt);
            }
        });

        jnewLastname.setBackground(new java.awt.Color(249, 249, 249));
        jnewLastname.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jnewLastname.setForeground(new java.awt.Color(153, 153, 153));
        jnewLastname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jnewLastname.setText("Lastname");
        jnewLastname.setToolTipText("");
        jnewLastname.setBorder(null);

        jnewEmail.setBackground(new java.awt.Color(249, 249, 249));
        jnewEmail.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jnewEmail.setForeground(new java.awt.Color(153, 153, 153));
        jnewEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jnewEmail.setText("Email");
        jnewEmail.setToolTipText("");
        jnewEmail.setBorder(null);

        jbackmenu.setFont(new java.awt.Font("Comfortaa", 0, 10)); // NOI18N
        jbackmenu.setForeground(new java.awt.Color(102, 102, 102));
        jbackmenu.setText("Back to menu");
        jbackmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbackmenuMouseClicked(evt);
            }
        });

        jnewrol.setBackground(new java.awt.Color(249, 249, 249));
        jnewrol.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jnewrol.setForeground(new java.awt.Color(153, 153, 153));
        jnewrol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal user", "Team lead user", "Team member user" }));
        jnewrol.setBorder(null);
        jnewrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnewrolActionPerformed(evt);
            }
        });

        jnewAge.setBackground(new java.awt.Color(249, 249, 249));
        jnewAge.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jnewAge.setForeground(new java.awt.Color(153, 153, 153));
        jnewAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jnewAge.setText("Edad");
        jnewAge.setToolTipText("");
        jnewAge.setBorder(null);
        jnewAge.setEnabled(false);

        jnewDepartament.setBackground(new java.awt.Color(249, 249, 249));
        jnewDepartament.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jnewDepartament.setForeground(new java.awt.Color(153, 153, 153));
        jnewDepartament.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select department", "Sales", "RRHH", "IT", "Accounting" }));
        jnewDepartament.setBorder(null);
        jnewDepartament.setEnabled(false);
        jnewDepartament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnewDepartamentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdivclassLayout = new javax.swing.GroupLayout(jdivclass);
        jdivclass.setLayout(jdivclassLayout);
        jdivclassLayout.setHorizontalGroup(
            jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdivclassLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbackmenu)
                .addGap(231, 231, 231))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdivclassLayout.createSequentialGroup()
                .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jdivclassLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btcreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdivclassLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdivclassLayout.createSequentialGroup()
                                .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdivclassLayout.createSequentialGroup()
                                        .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtitle)
                                            .addComponent(jsubtitle))
                                        .addGap(40, 40, 40))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jnewUser, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jnewPassword)
                                        .addComponent(jnewName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jnewLastname, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                        .addComponent(jnewEmail, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jnewAge)
                                    .addComponent(jnewDepartament, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jnewrol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        jdivclassLayout.setVerticalGroup(
            jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdivclassLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdivclassLayout.createSequentialGroup()
                        .addComponent(jnewName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jnewLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jnewAge, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jnewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jnewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jnewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jnewrol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btcreate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jbackmenu))
                    .addGroup(jdivclassLayout.createSequentialGroup()
                        .addComponent(jnewDepartament, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jbackgroundLayout = new javax.swing.GroupLayout(jbackground);
        jbackground.setLayout(jbackgroundLayout);
        jbackgroundLayout.setHorizontalGroup(
            jbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbackgroundLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jdivclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jbackgroundLayout.setVerticalGroup(
            jbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbackgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jdivclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnewUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnewUserActionPerformed

    private void btcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcreateActionPerformed
        // TODO add your handling code here:

        
        
        boolean userexist = false;

        for(newusers u: masterclass.users){
            if(u.getEmail().equals(jnewEmail.getText())||u.getUser().equals(jnewUser.getText())){
                userexist = true;
                break;
            }
        }
        if(userexist){
            JOptionPane.showMessageDialog(this, "The email or user entered is already registered, please enter a new one.");
        }else{
            
            //Password validation
            String PATTERN = "^(?=.*[AZ])(?=.*[az])(?=.*[0-9]).{8,20}$";
            Pattern patt = Pattern.compile(PATTERN);
            Matcher match = patt.matcher(jnewPassword.getText());
            /////////////////////
            if(!match.matches()){
                JOptionPane.showMessageDialog(this, "Password format incorrect, try again.");
            }else{
            newusers user = new newusers();
            user.setName(jnewName.getText());
            user.setLastname(jnewLastname.getText());
            user.setEmail(jnewEmail.getText());
            user.setUser(jnewUser.getText());
            user.setPassword(jnewPassword.getText());
            user.setRol(jnewrol.getSelectedItem().toString());
            if(jnewrol.getSelectedItem().equals("Team member user")){
                user.setDepartament(jnewDepartament.getSelectedItem().toString());
            }else if(jnewrol.getSelectedItem().equals("Team lead user")){
                user.setAge(jnewAge.getText());
            }
            masterclass.users.add(user);

            jnewName.setText("Name");
            jnewLastname.setText("Lastname");
            jnewEmail.setText("Email");
            jnewUser.setText("User");
            jnewPassword.setText("Password");
            jnewAge.setText("Age");
            jnewDepartament.setSelectedItem("Select department");

            JOptionPane.showMessageDialog(this, "New user created successfully");
            }
        }
    }//GEN-LAST:event_btcreateActionPerformed

    private void jnewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnewPasswordActionPerformed

    private void jbackmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbackmenuMouseClicked
        // TODO add your handling code here:
        menuadmin m = new menuadmin();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbackmenuMouseClicked

    private void jnewrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnewrolActionPerformed
        // TODO add your handling code here:
        if(jnewrol.getSelectedItem().equals("Team member user")){
            jnewDepartament.setEnabled(true);
        }else{
            jnewDepartament.setEnabled(false);
        }
        
        if (jnewrol.getSelectedItem().equals("Team lead user")) {
            jnewAge.setEnabled(true);
        } else {
            jnewAge.setEnabled(false);
        }
    }//GEN-LAST:event_jnewrolActionPerformed

    private void jnewDepartamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnewDepartamentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnewDepartamentActionPerformed

    private void jnewNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnewNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnewNameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcreate;
    private javax.swing.JPanel jbackground;
    private javax.swing.JLabel jbackmenu;
    private javax.swing.JPanel jdivclass;
    private javax.swing.JTextField jnewAge;
    private javax.swing.JComboBox<String> jnewDepartament;
    private javax.swing.JTextField jnewEmail;
    private javax.swing.JTextField jnewLastname;
    private javax.swing.JTextField jnewName;
    private javax.swing.JPasswordField jnewPassword;
    private javax.swing.JTextField jnewUser;
    private javax.swing.JComboBox<String> jnewrol;
    private javax.swing.JLabel jsubtitle;
    private javax.swing.JLabel jtitle;
    // End of variables declaration//GEN-END:variables
}
