/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.imbochfckyeahprojects.finalproject;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author imbochfuckyeah
 */
public class createticket extends javax.swing.JFrame {

    private int count = 1;

    /**
     * Creates new form createuser
     */
    public createticket() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbackground = new javax.swing.JPanel();
        jdivclass = new javax.swing.JPanel();
        jtitle = new javax.swing.JLabel();
        jsubtitle = new javax.swing.JLabel();
        btcreate = new javax.swing.JButton();
        jnewTitle = new javax.swing.JTextField();
        jbackmenu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jnewDescript = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbackground.setBackground(new java.awt.Color(0, 153, 204));

        jdivclass.setBackground(new java.awt.Color(255, 255, 255));

        jtitle.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jtitle.setForeground(new java.awt.Color(102, 102, 102));
        jtitle.setText("Create new ticket");

        jsubtitle.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jsubtitle.setForeground(new java.awt.Color(0, 153, 204));
        jsubtitle.setText("Create new ticket now");

        btcreate.setBackground(new java.awt.Color(0, 153, 204));
        btcreate.setFont(new java.awt.Font("Montserrat", 1, 15)); // NOI18N
        btcreate.setForeground(new java.awt.Color(255, 255, 255));
        btcreate.setText("Create ticket");
        btcreate.setBorder(null);
        btcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcreateActionPerformed(evt);
            }
        });

        jnewTitle.setBackground(new java.awt.Color(249, 249, 249));
        jnewTitle.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jnewTitle.setForeground(new java.awt.Color(153, 153, 153));
        jnewTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jnewTitle.setText("Title");
        jnewTitle.setToolTipText("");
        jnewTitle.setBorder(null);
        jnewTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnewTitleActionPerformed(evt);
            }
        });

        jbackmenu.setFont(new java.awt.Font("Comfortaa", 0, 10)); // NOI18N
        jbackmenu.setForeground(new java.awt.Color(102, 102, 102));
        jbackmenu.setText("Back to menu");
        jbackmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbackmenuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbackmenuMousePressed(evt);
            }
        });

        jnewDescript.setBackground(new java.awt.Color(249, 249, 249));
        jnewDescript.setColumns(20);
        jnewDescript.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jnewDescript.setForeground(new java.awt.Color(153, 153, 153));
        jnewDescript.setRows(5);
        jnewDescript.setText("Type here your problem");
        jnewDescript.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        jnewDescript.setDisabledTextColor(new java.awt.Color(249, 249, 249));
        jScrollPane1.setViewportView(jnewDescript);

        javax.swing.GroupLayout jdivclassLayout = new javax.swing.GroupLayout(jdivclass);
        jdivclass.setLayout(jdivclassLayout);
        jdivclassLayout.setHorizontalGroup(
            jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdivclassLayout.createSequentialGroup()
                .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jdivclassLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jnewTitle))
                    .addGroup(jdivclassLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtitle)
                            .addComponent(jsubtitle)))
                    .addGroup(jdivclassLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btcreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jdivclassLayout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jbackmenu)
                                .addGap(123, 123, 123))))
                    .addGroup(jdivclassLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jdivclassLayout.setVerticalGroup(
            jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdivclassLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jnewTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btcreate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbackmenu)
                .addContainerGap())
        );

        javax.swing.GroupLayout jbackgroundLayout = new javax.swing.GroupLayout(jbackground);
        jbackground.setLayout(jbackgroundLayout);
        jbackgroundLayout.setHorizontalGroup(
            jbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbackgroundLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jdivclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jbackgroundLayout.setVerticalGroup(
            jbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbackgroundLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jdivclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcreateActionPerformed
        // TODO add your handling code here:
        crateticket();
    }//GEN-LAST:event_btcreateActionPerformed

    private void jbackmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbackmenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbackmenuMouseClicked

    private void jnewTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnewTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnewTitleActionPerformed

    private void jbackmenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbackmenuMousePressed
        // TODO add your handling code here:
        menuusers view = new menuusers(menuusers.user);
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbackmenuMousePressed

    public void crateticket(){
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");  
        Date date = new Date(); 
        newticket ticket = new newticket();
        ticket.setId(count++);
        ticket.setTitle(jnewTitle.getText());
        ticket.setDescrip(jnewDescript.getText());
        ticket.setStartdate(formatter.format(date));
        ticket.setUsercreated(menuusers.usercockie);
        ticket.setUserasigned("");
        ticket.setStatus("Not assigned");
        ticket.setFinishdate("");
        
        //add ticket
        masterclass.ticket.add(ticket);
        jnewTitle.setText("Title");
        jnewDescript.setText("Type here your problem");
        JOptionPane.showMessageDialog(this, "New user created successfully");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcreate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jbackground;
    private javax.swing.JLabel jbackmenu;
    private javax.swing.JPanel jdivclass;
    private javax.swing.JTextArea jnewDescript;
    private javax.swing.JTextField jnewTitle;
    private javax.swing.JLabel jsubtitle;
    private javax.swing.JLabel jtitle;
    // End of variables declaration//GEN-END:variables
}
