/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.imbochfckyeahprojects.finalproject;

import javax.swing.*;

/**
 *
 * @author imbochfuckyeah
 */
public class createteam extends javax.swing.JFrame {

    /**
     * Creates new form createteam
     */
    public createteam() {
        initComponents();
        this.setLocationRelativeTo(null);
        setComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbackground = new javax.swing.JPanel();
        jdivclass = new javax.swing.JPanel();
        jtitle = new javax.swing.JLabel();
        jsubtitle = new javax.swing.JLabel();
        btcreate = new javax.swing.JButton();
        jnewTeam = new javax.swing.JTextField();
        jnewleader = new javax.swing.JComboBox<>();
        jbackmenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbackground.setBackground(new java.awt.Color(0, 153, 204));

        jdivclass.setBackground(new java.awt.Color(255, 255, 255));

        jtitle.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jtitle.setForeground(new java.awt.Color(102, 102, 102));
        jtitle.setText("Create new team");

        jsubtitle.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jsubtitle.setForeground(new java.awt.Color(0, 153, 204));
        jsubtitle.setText("Create new team with leader");

        btcreate.setBackground(new java.awt.Color(0, 153, 204));
        btcreate.setFont(new java.awt.Font("Montserrat", 1, 15)); // NOI18N
        btcreate.setForeground(new java.awt.Color(255, 255, 255));
        btcreate.setText("Create team");
        btcreate.setBorder(null);
        btcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcreateActionPerformed(evt);
            }
        });

        jnewTeam.setBackground(new java.awt.Color(249, 249, 249));
        jnewTeam.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jnewTeam.setForeground(new java.awt.Color(153, 153, 153));
        jnewTeam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jnewTeam.setText("Team Name");
        jnewTeam.setToolTipText("");
        jnewTeam.setBorder(null);
        jnewTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnewTeamActionPerformed(evt);
            }
        });

        jnewleader.setBackground(new java.awt.Color(249, 249, 249));
        jnewleader.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jnewleader.setForeground(new java.awt.Color(153, 153, 153));
        jnewleader.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select leader of team", " " }));
        jnewleader.setBorder(null);

        jbackmenu.setFont(new java.awt.Font("Comfortaa", 0, 10)); // NOI18N
        jbackmenu.setForeground(new java.awt.Color(102, 102, 102));
        jbackmenu.setText("Back to menu");
        jbackmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbackmenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jdivclassLayout = new javax.swing.GroupLayout(jdivclass);
        jdivclass.setLayout(jdivclassLayout);
        jdivclassLayout.setHorizontalGroup(
            jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdivclassLayout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(jbackmenu)
                .addGap(120, 120, 120))
            .addGroup(jdivclassLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdivclassLayout.createSequentialGroup()
                        .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtitle)
                            .addComponent(jsubtitle))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btcreate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jnewTeam, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jnewleader, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdivclassLayout.setVerticalGroup(
            jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdivclassLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(jtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jnewTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jnewleader, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btcreate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jbackmenu)
                .addContainerGap())
        );

        javax.swing.GroupLayout jbackgroundLayout = new javax.swing.GroupLayout(jbackground);
        jbackground.setLayout(jbackgroundLayout);
        jbackgroundLayout.setHorizontalGroup(
            jbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbackgroundLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jdivclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jbackgroundLayout.setVerticalGroup(
            jbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbackgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jdivclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setComboBox(){
        jnewleader.setModel(new DefaultComboBoxModel<>(new String[]{
                "Select leader",
        }));

        for (newusers u : masterclass.users) {
            if (u.getRol().equals("Team lead user")) {
                jnewleader.addItem(u.getUser());
            }
        }
    }

    private void btcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcreateActionPerformed
        // TODO add your handling code here:

        boolean teamexist = false;

        for(newteam t: masterclass.team){
            if(t.getTeamname().equals(jnewTeam.getText())){
                teamexist = true;
                break;
            }
        }
        if(teamexist){
            JOptionPane.showMessageDialog(this, "The name team entered is already registered, please enter a new one.");
        }else if(jnewTeam.getText().equals("Team Name") || jnewTeam.getText().isEmpty() || jnewTeam.getText().isBlank() ){
            JOptionPane.showMessageDialog(this, "Please choose a lead user");
        }else if(jnewleader.getSelectedItem().toString().equals("Select leader")){
            JOptionPane.showMessageDialog(this, "Please choose a lead user");
        }else{
            newteam nteam = new newteam();
            nteam.setTeamname(jnewTeam.getText());
            nteam.setLeaderofteam(jnewleader.getSelectedItem().toString());
            masterclass.team.add(nteam);

            for(newusers u : masterclass.users){
                if(u.getUser().equals(jnewleader.getSelectedItem().toString())){
                    u.setTeam(jnewTeam.getText());
                }
            }

            jnewTeam.setText("Team Name");

            JOptionPane.showMessageDialog(this, "New Team created successfully");
        }

        /*for(newteam t: masterclass.team){
            System.out.println(t.getTeamname());
            System.out.println(t.getLeaderofteam());
        }*/
    }//GEN-LAST:event_btcreateActionPerformed

    private void jbackmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbackmenuMouseClicked
        // TODO add your handling code here:
        menuadmin m = new menuadmin();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbackmenuMouseClicked

    private void jnewTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnewTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnewTeamActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcreate;
    private javax.swing.JPanel jbackground;
    private javax.swing.JLabel jbackmenu;
    private javax.swing.JPanel jdivclass;
    private javax.swing.JTextField jnewTeam;
    private javax.swing.JComboBox<String> jnewleader;
    private javax.swing.JLabel jsubtitle;
    private javax.swing.JLabel jtitle;
    // End of variables declaration//GEN-END:variables
}
