/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.imbochfckyeahprojects.finalproject;

import javax.swing.JOptionPane;

/**
 *
 * @author imbochfuckyeah
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbackground = new javax.swing.JPanel();
        jdivclass = new javax.swing.JPanel();
        jtitle = new javax.swing.JLabel();
        jsubtitle = new javax.swing.JLabel();
        jUser = new javax.swing.JTextField();
        jforgotpass = new javax.swing.JLabel();
        btsubmit = new javax.swing.JButton();
        jnewaccount = new javax.swing.JLabel();
        jpassword = new javax.swing.JPasswordField();
        windowbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jbackground.setBackground(new java.awt.Color(0, 153, 204));

        jdivclass.setBackground(new java.awt.Color(255, 255, 255));

        jtitle.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jtitle.setForeground(new java.awt.Color(102, 102, 102));
        jtitle.setText("Login");

        jsubtitle.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jsubtitle.setForeground(new java.awt.Color(0, 153, 204));
        jsubtitle.setText("login with you account");

        jUser.setBackground(new java.awt.Color(249, 249, 249));
        jUser.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jUser.setForeground(new java.awt.Color(153, 153, 153));
        jUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jUser.setText("User or Email");
        jUser.setToolTipText("");
        jUser.setBorder(null);

        jforgotpass.setFont(new java.awt.Font("Comfortaa", 0, 10)); // NOI18N
        jforgotpass.setForeground(new java.awt.Color(102, 102, 102));
        jforgotpass.setText("Forgot password?");

        btsubmit.setBackground(new java.awt.Color(0, 153, 204));
        btsubmit.setFont(new java.awt.Font("Montserrat", 1, 15)); // NOI18N
        btsubmit.setForeground(new java.awt.Color(255, 255, 255));
        btsubmit.setText("Submit");
        btsubmit.setBorder(null);
        btsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsubmitActionPerformed(evt);
            }
        });

        jnewaccount.setFont(new java.awt.Font("Comfortaa", 0, 10)); // NOI18N
        jnewaccount.setForeground(new java.awt.Color(102, 102, 102));
        jnewaccount.setText("You still don't have an account? create account");
        jnewaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jnewaccountMouseClicked(evt);
            }
        });

        jpassword.setBackground(new java.awt.Color(249, 249, 249));
        jpassword.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jpassword.setForeground(new java.awt.Color(153, 153, 153));
        jpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpassword.setText("Password");
        jpassword.setBorder(null);
        jpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdivclassLayout = new javax.swing.GroupLayout(jdivclass);
        jdivclass.setLayout(jdivclassLayout);
        jdivclassLayout.setHorizontalGroup(
            jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdivclassLayout.createSequentialGroup()
                .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdivclassLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jnewaccount))
                    .addGroup(jdivclassLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdivclassLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtitle)
                                    .addComponent(jsubtitle))
                                .addGap(59, 59, 59))
                            .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jforgotpass)
                                .addComponent(jUser, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btsubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdivclassLayout.setVerticalGroup(
            jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdivclassLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jforgotpass)
                .addGap(42, 42, 42)
                .addComponent(jnewaccount)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jbackgroundLayout = new javax.swing.GroupLayout(jbackground);
        jbackground.setLayout(jbackgroundLayout);
        jbackgroundLayout.setHorizontalGroup(
            jbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbackgroundLayout.createSequentialGroup()
                .addGroup(jbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(windowbg)
                    .addGroup(jbackgroundLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jdivclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jbackgroundLayout.setVerticalGroup(
            jbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbackgroundLayout.createSequentialGroup()
                .addComponent(windowbg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdivclass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsubmitActionPerformed
        // TODO add your handling code here:
        String user = jUser.getText();
        String password = jpassword.getText();

        if("admin".equals(user)&&"admin".equals(password)){
            menuusers.usercoockie = "admin";
            menuusers.rolcoockie = "admin";
            menuadmin m = new menuadmin();
            m.setVisible(true);
            this.dispose();
        }else{
            boolean userexist = false;
            for(newusers u: masterclass.users){
                if(u.getPassword().equals(password) && u.getUser().equals(user) || u.getEmail().equals(user) && u.getPassword().equals(password)){
                    menuusers w = new menuusers(u);
                    w.setVisible(true);
                    userexist = true;
                    break;
                }
            }if(userexist){
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "User or Password incorrect");
            }
        }
    }//GEN-LAST:event_btsubmitActionPerformed
    
    private void jnewaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jnewaccountMouseClicked
        // TODO add your handling code here
        singup s = new singup();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jnewaccountMouseClicked

    private void jpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasswordActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btsubmit;
    private javax.swing.JTextField jUser;
    private javax.swing.JPanel jbackground;
    private javax.swing.JPanel jdivclass;
    private javax.swing.JLabel jforgotpass;
    private javax.swing.JLabel jnewaccount;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JLabel jsubtitle;
    private javax.swing.JLabel jtitle;
    private javax.swing.JLabel windowbg;
    // End of variables declaration//GEN-END:variables
}
