/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.imbochfckyeahprojects.finalproject;

import java.util.regex.*;
import javax.swing.JOptionPane;

/**
 *
 * @author imbochfuckyeah
 */
public class singup extends javax.swing.JFrame {

    /**
     * Creates new form singup
     */
    public singup() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbackground = new javax.swing.JPanel();
        jdivclass = new javax.swing.JPanel();
        jtitle = new javax.swing.JLabel();
        jsubtitle = new javax.swing.JLabel();
        jnewUser = new javax.swing.JTextField();
        btcreate = new javax.swing.JButton();
        jnewPassword = new javax.swing.JPasswordField();
        jnewaccount = new javax.swing.JLabel();
        jnewName = new javax.swing.JTextField();
        jnewLastname = new javax.swing.JTextField();
        jnewEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbackground.setBackground(new java.awt.Color(0, 153, 204));

        jdivclass.setBackground(new java.awt.Color(255, 255, 255));

        jtitle.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jtitle.setForeground(new java.awt.Color(102, 102, 102));
        jtitle.setText("SingUp");

        jsubtitle.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jsubtitle.setForeground(new java.awt.Color(0, 153, 204));
        jsubtitle.setText("create your new account");

        jnewUser.setBackground(new java.awt.Color(249, 249, 249));
        jnewUser.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jnewUser.setForeground(new java.awt.Color(153, 153, 153));
        jnewUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jnewUser.setText("User");
        jnewUser.setToolTipText("");
        jnewUser.setBorder(null);
        jnewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnewUserActionPerformed(evt);
            }
        });

        btcreate.setBackground(new java.awt.Color(0, 153, 204));
        btcreate.setFont(new java.awt.Font("Montserrat", 1, 15)); // NOI18N
        btcreate.setForeground(new java.awt.Color(255, 255, 255));
        btcreate.setText("Create user");
        btcreate.setBorder(null);
        btcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcreateActionPerformed(evt);
            }
        });

        jnewPassword.setBackground(new java.awt.Color(249, 249, 249));
        jnewPassword.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jnewPassword.setForeground(new java.awt.Color(153, 153, 153));
        jnewPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jnewPassword.setText("password");
        jnewPassword.setBorder(null);
        jnewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnewPasswordActionPerformed(evt);
            }
        });

        jnewaccount.setFont(new java.awt.Font("Comfortaa", 0, 10)); // NOI18N
        jnewaccount.setForeground(new java.awt.Color(102, 102, 102));
        jnewaccount.setText("LogIn with your account");
        jnewaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jnewaccountMouseClicked(evt);
            }
        });

        jnewName.setBackground(new java.awt.Color(249, 249, 249));
        jnewName.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jnewName.setForeground(new java.awt.Color(153, 153, 153));
        jnewName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jnewName.setText(" Name");
        jnewName.setToolTipText("");
        jnewName.setBorder(null);

        jnewLastname.setBackground(new java.awt.Color(249, 249, 249));
        jnewLastname.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jnewLastname.setForeground(new java.awt.Color(153, 153, 153));
        jnewLastname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jnewLastname.setText("Lastname");
        jnewLastname.setToolTipText("");
        jnewLastname.setBorder(null);

        jnewEmail.setBackground(new java.awt.Color(249, 249, 249));
        jnewEmail.setFont(new java.awt.Font("Comfortaa", 0, 15)); // NOI18N
        jnewEmail.setForeground(new java.awt.Color(153, 153, 153));
        jnewEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jnewEmail.setText("Email");
        jnewEmail.setToolTipText("");
        jnewEmail.setBorder(null);

        javax.swing.GroupLayout jdivclassLayout = new javax.swing.GroupLayout(jdivclass);
        jdivclass.setLayout(jdivclassLayout);
        jdivclassLayout.setHorizontalGroup(
            jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdivclassLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdivclassLayout.createSequentialGroup()
                        .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtitle)
                            .addComponent(jsubtitle))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdivclassLayout.createSequentialGroup()
                        .addComponent(jnewaccount)
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdivclassLayout.createSequentialGroup()
                        .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btcreate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jnewUser, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jnewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addComponent(jnewName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jnewLastname)
                                .addComponent(jnewEmail, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(25, 25, 25))))
        );
        jdivclassLayout.setVerticalGroup(
            jdivclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdivclassLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jnewName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jnewLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jnewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jnewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jnewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btcreate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jnewaccount)
                .addContainerGap())
        );

        javax.swing.GroupLayout jbackgroundLayout = new javax.swing.GroupLayout(jbackground);
        jbackground.setLayout(jbackgroundLayout);
        jbackgroundLayout.setHorizontalGroup(
            jbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbackgroundLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jdivclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jbackgroundLayout.setVerticalGroup(
            jbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbackgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jdivclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnewUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnewUserActionPerformed

    private void btcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcreateActionPerformed
        // TODO add your handling code here:

        boolean userexist = false;

        for(newusers u: masterclass.users){
            if(u.getEmail().equals(jnewEmail.getText())||u.getUser().equals(jnewUser.getText())){
                userexist = true;
                break;
            }
        }
        if(userexist){
            JOptionPane.showMessageDialog(this, "The email or user entered is already registered, please enter a new one.");
        }else{
            //Password validation
            String PATTERN = "^(?=.*[AZ])(?=.*[az])(?=.*[0-9]).{8,20}$";
            Pattern patt = Pattern.compile(PATTERN);
            Matcher match = patt.matcher(jnewPassword.getText());
            /////////////////////
            if(!match.matches()){
                JOptionPane.showMessageDialog(this, "Password format incorrect, try again.");
            }else{
            newusers user = new newusers();
            user.setName(jnewName.getText());
            user.setLastname(jnewLastname.getText());
            user.setEmail(jnewEmail.getText());
            user.setUser(jnewUser.getText());
            user.setPassword(jnewPassword.getText());
            user.setRol("Usuario normal");
            masterclass.users.add(user);

            jnewName.setText("Name");
            jnewLastname.setText("Lastname");
            jnewEmail.setText("Email");
            jnewUser.setText("User");
            jnewPassword.setText("P assword");

            JOptionPane.showMessageDialog(this, "New user created successfully");
            }
        }
    }//GEN-LAST:event_btcreateActionPerformed

    private void jnewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnewPasswordActionPerformed

    private void jnewaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jnewaccountMouseClicked
        // TODO add your handling code here:
        login log = new login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jnewaccountMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcreate;
    private javax.swing.JPanel jbackground;
    private javax.swing.JPanel jdivclass;
    private javax.swing.JTextField jnewEmail;
    private javax.swing.JTextField jnewLastname;
    private javax.swing.JTextField jnewName;
    private javax.swing.JPasswordField jnewPassword;
    private javax.swing.JTextField jnewUser;
    private javax.swing.JLabel jnewaccount;
    private javax.swing.JLabel jsubtitle;
    private javax.swing.JLabel jtitle;
    // End of variables declaration//GEN-END:variables
}
